[package]
name = "dom_bindings"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["simd"]
simd = []

[dependencies]
js = { path = "../js", version = "0.1.0" }
html = { path = "../html", version = "0.1.0" }
css = { path = "../css", version = "0.1.0" }
url = "2"
base64 = "0.22"
sha2 = "0.10"

[lints]
workspace = true
