[package]
name = "css-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
css = { path = "..", version = "0.1.0" }
html = { path = "../../html", version = "0.1.0" }
url = "2"

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"

[workspace]
