[package]
name = "shell"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[features]
default = ["simd"]
simd = []

[dependencies]
net = { path = "../net", version = "0.1.0" }
html = { path = "../html", version = "0.1.0" }
css = { path = "../css", version = "0.1.0" }
layout = { path = "../layout", version = "0.1.0" }
paint = { path = "../paint", version = "0.1.0" }
js = { path = "../js", version = "0.1.0" }
dom_bindings = { path = "../dom_bindings", version = "0.1.0" }
pollster = "0.4"
encoding_rs = "0.8"
flate2 = "1"
base64 = "0.22"
percent-encoding = "2"
woff2-patched = "0.4"
brotli = "7"
url = "2"
winit = "0.30"
softbuffer = "0.4"
cosmic-text = "0.12"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "sync"] }
thiserror = "2"

[lints]
workspace = true

[dev-dependencies]
tokio = { version = "1", features = ["net", "io-util", "macros"] }
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.3", features = ["client"] }
